# Generated by Django 4.2.5 on 2023-10-02 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finaleA15Service", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="name",
        ),
    ]
